---
beet_project: silverstripe
beet_domain: "silverstripe.local"
beet_root: "{{ beet_base }}/docroot"
ss_create_project: yes
ss_install_site: yes
ss_account_name: admin
ss_account_pass: admin
beet_mysql_user: root
beet_mysql_password: ""

# PHP 7 config.
php_version: "7.0"
php_packages:
  - php7.0
  - libapache2-mod-php7.0
  - php7.0-cli
  - php7.0-common
  - php7.0-curl
  - php7.0-dev
  - php7.0-fpm
  - php7.0-gd
  - php7.0-json
  - php7.0-opcache
  - libpcre3-dev
php_mysql_package: php7.0-mysql
php_fpm_daemon: php7.0-fpm
