---
beet_project: silverstripe
beet_domain: "silverstripe.local"
beet_root: "{{ beet_base }}/docroot"
ss_create_project: yes
ss_install_site: yes
ss_account_name: admin
ss_account_pass: admin
beet_mysql_user: root
beet_mysql_password: ""
php_packages:
  - php5
  - libapache2-mod-php5
  - php5-mcrypt
  - php5-cli
  - php5-common
  - php5-curl
  - php5-dev
  - php5-fpm
  - php5-gd
  - php5-intl
  - php5-tidy
  - php-pear
  - php-apc
  - libpcre3-dev
